[build]
  base = "frontend"
  command = "npm install && npx react-scripts build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200