[build]
  base = "frontend"
  command = "npm ci && chmod +x node_modules/.bin/react-scripts && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200